/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mwfekmiyuiknmahflvom"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13ZmVrbWl5dWlrbm1haGZsdm9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgzMDAyOTMsImV4cCI6MjA5Mzg3NjI5M30.8t-tpR31hO1LZPsfZd4KQoW7s5YhBDprdO8fmT7HKlw"
